return {
    SNAP_RADIUS = 2,
    MAX_PIPE_LENGTH = 20,
    MIN_PIPE_HINGE_ANGLE = math.cos(math.rad(70)),
    BLUEPRINT_TRANSPARENCY = 0.7,
    PIPE_COLORS = {
        default = BrickColor.new("Medium brown"),
        hologramValid = BrickColor.new("Shamrock"),
        hologramInvalid = BrickColor.new("Burgundy")
    },
    KEYBINDS = {
        cancel = Enum.KeyCode.Escape,
        pipe = Enum.KeyCode.Z,
        junct3 = Enum.KeyCode.X,
        junct4 = Enum.KeyCode.C
    }
}